### ISSUE TITLE
other look for the block

### ISSUE THREAD

**Issue by thebigalwisi** [5hir0kur0/logseq-time-recorder#2]
hi 5hir0kur0,

I discovered your plugin today, great thing. Exactly what I was looking for, almost...

I often work on a laptop with a small screen, for me personally and many others too, it would be more advantageous if you could make the bordered block a little smaller/narrower (see first image).
![image](https://github.com/5hir0kur0/logseq-time-recorder/assets/85204944/1d18cdb0-77cf-4c12-b4cf-73f1e9c13cff)

If this would contain the individual timeslots, but would only be displayed by a click (see second and third image).
![image](https://github.com/5hir0kur0/logseq-time-recorder/assets/85204944/5c8693e9-2df8-467a-8316-1cf8aaed72d1)
![image](https://github.com/5hir0kur0/logseq-time-recorder/assets/85204944/2f2159c1-7900-4975-a84a-abeb5c398f39)

Furthermore, it would be a big plus if at the end the block the corresponding date, total time and possibly a #Tag in text would be saved in order to be able to do something with it even with quieries (see forth image). Maybe so, I am not sure if that is helpful for queries.
![image](https://github.com/5hir0kur0/logseq-time-recorder/assets/85204944/96f2ce23-8984-437b-9217-b35c82e5f226)

Unfortunately I can't programme and therefore can't help. But I would be very grateful if you could implement this. Perhaps as a choice between your original display (which I think is quite nice) and the one I described.

**Comment by 5hir0kur0** [comment]
@thebigalwisi 

Thanks for the suggestion, I like the idea!
I'm a bit short on time right now (thesis, job, ...) but I might look into this in a few months when I have more time.

I see that you're using it quite late at night. Currently the timestamps are just stored as `HH:MM` and it's assumed that they're _all on the same day_, so e.g. clocking in at `23:00` and clocking out at `01:00` won't work and you'll get this error:
![image](https://github.com/5hir0kur0/logseq-time-recorder/assets/12101162/11b8842d-d139-4711-bb94-dd260a8a62b3)

(For me personally that's not a big limitation since I'm only using this to track the time I spend working on certain tasks during my day job, but I'd still like to implement support for full timestamps including the date eventually.)

**Comment by thebigalwisi** [comment]
Hi @5hir0kur0 

Great! I'll be waiting ;-) Thanks!
The late primeval period was for demonstration purposes only. For work, the topic doesn't matter to me.

**Comment by 5hir0kur0** [comment]
I think with #3 it's possible to do something close to what you wanted.
If you set the `blockTemplate` in the settings to
```
{{{time-recorder}}}
#time-recorder {{{today}}}
```

You would get the following if you create a new Time Recorder:
```
{{renderer :time-recorder, 15:06}} 
#time-recorder [[May 31st, 2024]]
```
![image](https://github.com/5hir0kur0/logseq-time-recorder/assets/12101162/f7a564ac-59c6-4d1d-83ae-2c803136f503)

**Comment by thebigalwisi** [comment]
Hi @5hir0kur0,

Sorry, I was a bit absent this time. Many thanks for your work! It looks great! 


... but I'm a bit confused: I can't find settings for Time Recorder!?

**Comment by thebigalwisi** [comment]
... hm, it's certainly not what the creator intended, but uninstalling and reinstalling helped! :-D

Could you perhaps add a column in which you can write something down, e.g. for which project you worked in a time slot?

**Comment by 5hir0kur0** [comment]
Hi @thebigalwisi,

sorry for responding so late.
That would be quite far from my own use-case, so I think I'm not going to implement that.

However, since the code is open-source anyone is free to make a fork with that feature.

In the rare case when I need to track separate tasks I just make separate time recorders for each task (and one for the whole day) like this:
![example](https://github.com/user-attachments/assets/fc077dc7-8671-4d2b-990b-adbb71354c86)
